# Generated by Django 6.0.2 on 2026-03-06 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatie',
            name='timp_standard',
            field=models.DurationField(default=datetime.timedelta, help_text='Timpul standard în minute'),
        ),
    ]
