# Generated by Django 6.0.2 on 2026-03-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_operatie_timp_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piesa', models.CharField(max_length=200)),
                ('timp_lucrat', models.DurationField()),
                ('timp_standard', models.DurationField()),
                ('data_finalizare', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.comanda')),
                ('mecanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mecanicul')),
                ('operatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.operatie')),
            ],
        ),
    ]
